AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'elb-health-check.gemspec'
  NewCops: enable

Layout/LineLength:
  Max: 100

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

